title: android-test
description: >-
  This course guides the learner on refactoring an android project to Compose
  and adding a Column of text.
template:
  repo: lab_test
  name: android-test-course
  description: This is a blank activity to get you started
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Visit the repo
    description: 'Visit the repo and clone it '
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
