title: android-test
description: >-
  This course guides the learner on refactoring an android project to Compose
  and adding a Column of text.
template:
  repo: lab_test
  name: android-trial-course
  description: This is a blank activity to get you started
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Visit the repo
    description: 'Visit the repo and clone it '
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: createIssue
        title: 2) Branch and push
        body: step-two.md
  - title: 2) Create branch staging and push
    description: Create a staging branch and push
    event: push
    actions:
      - type: respond
        with: step-two.md
        store:
          branch: '%payload.ref%'
        issue: 2) Branch and push 
      - type: gate
        left: '{{ store.branch }}'
        operator: ===
        right: 'staging'
        every: true
        else:
          - type: respond
            with: wrong-branch.md
      - type: closeIssue
        issue: 2) Branch and push
